### ISSUE TITLE
MakeFile Issue

### ISSUE THREAD

**Issue by NeoGeoFreak2004** [city41/neo-geo-dev-book#3]
Sorry if this is the wrong place to put this error, But anyways. so i did everything the tutorial on the Hello World Program told me to do but when i type in make srom in the terminal it gives me a error. This error says: "cd .. && sromcrom -i resources/resources.json
/bin/sh: 1: sromcrom: not found
make: *** [Makefile:36: srom] Error 1" I don't know what to do for this error so can you help me with error!

**Comment by city41** [comment]
Thanks for trying out the book. But it is very early at this point and I wouldn't recommend trying to read it yet. I'll add a disclaimer to it. [Chapter 3](https://neogeobook.mattgreer.dev/book/03-installing-the-tools) will show how to install sromcrom, but I haven't written it yet.

To install it, you need to [install nodejs](https://nodejs.org/en/download/) then run `npm install -g @city41/sromcrom`

But even with it installed, you're sure to run into more problems. I haven't proof read the book, verified the code is correct, or anything like that at this point.

**Comment by NeoGeoFreak2004** [comment]
Thanks, I will try to install it when I get home. Also does ngdevkit support the memory card?

**Comment by NeoGeoFreak2004** [comment]
Update On The sromcrom installation situation: when i type in the command you give me to install the tools it gives me a npm error. IDK why this happens to me.
