### ISSUE TITLE
Neosprite installation

### ISSUE THREAD

**Issue by NeoGeoFreak2004** [city41/neo-geo-dev-book#5]
Hey yall so anyways, I want to install the Neosprite program on Ubuntu so I can create my own sprites for Neo Geo games but how do I install it? Does it have to be npm like say sromcrom?

**Comment by city41** [comment]
Neosprite is the old name for sromcrom. Again, I feel I need to reiterate you're trying to work off a book that is maybe 10% done, if that. The chapter I mention Neosprite in is merely a few headings and nothing else after all.
